USE Online_Food_Delivery_Business_Analytics_System_PROJECT_DB;

-- PHASE 1 —EXPLORATORY ANALYSIS

-- The company wants to know:

-- 1.Total Revenue Generated by online food delivery app

SELECT SUM(order_amount-discount) AS Total_Revenue
FROM Orders;


-- 2. Total Orders Per City

SELECT r.city,
    COUNT(*) AS total_orders
FROM orders o
    JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

-- 3. Top 10 Customers by Spending

SELECT c.customer_id,
    c.name,
    SUM(o.order_amount - COALESCE(o.discount,0)) AS total_spent
FROM Orders o
    JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC LIMIT 10;


-- PHASE 2 — CUSTOMER SEGMENTATION

--1. Customer Category (Gold/Silver/Bronze)

WITH customer_spend
AS
(
    SELECT c.customer_id,
    c.name,
    SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) AS total_spent
FROM Orders o
    JOIN Customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name
)
SELECT customer_id, +
       name,
    total_spent,
    CASE
         WHEN total_spent >= 1000 THEN 'Gold'
         WHEN total_spent >= 500 THEN 'Silver'
         ELSE 'Bronze'
       END AS category
FROM customer_spend
ORDER BY total_spent DESC;

-- PHASE 3 — RESTAURANT PERFORMANCE

-- 1.Top 10 Restaurants by Revenue
WITH
    restaurant_revenue
    AS
    (
        SELECT r.restaurant_id,
            r.restaurant_name,
            r.city,
            SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) AS revenue,
            COUNT(*) AS total_orders
        FROM Orders o
            JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
        GROUP BY r.restaurant_id, r.restaurant_name, r.city
    )
SELECT restaurant_id,
    restaurant_name AS name,
    city,
    revenue,
    total_orders
FROM restaurant_revenue
ORDER BY revenue DESC
LIMIT 10;

-- 2. Average Rating vs Revenue

WITH restaurant_performance
AS
(
    SELECT r.restaurant_id,
    r.restaurant_name,
    r.city,
    AVG(r.rating) AS avg_rating,
    SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) AS revenue
FROM orders o
    JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city
)
SELECT restaurant_id,
    restaurant_name AS name,
    city,
    avg_rating,
    revenue
FROM restaurant_performance
ORDER BY avg_rating DESC, revenue DESC;

-- PHASE 4 — DELIVERY ANALYSIS

-- 1. Average Delivery Time Per City

SELECT r.city,
    ROUND(AVG(o.delivery_time), 2) AS avg_delivery_time_minutes,
    COUNT(*) AS total_deliveries,
    MIN(o.delivery_time) AS min_delivery_time,
    MAX(o.delivery_time) AS max_delivery_time,
    ROUND(STDDEV(o.delivery_time), 2) AS stddev_delivery_time
FROM Orders o
    JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
WHERE o.delivery_time IS NOT NULL
GROUP BY r.city
ORDER BY avg_delivery_time_minutes ASC;

-- 2. Average Rating vs Revenue

SELECT r.restaurant_id,
    r.restaurant_name AS name,
    r.city,
    r.rating AS avg_rating,
    SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) AS revenue,
    COUNT(*) AS total_orders
FROM Orders o
    JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city, r.rating
ORDER BY avg_rating DESC, revenue DESC;

-- PHASE 5 — PAYMENT & DISCOUNT ANALYSIS

-- 1.Payment Method Distribution

SELECT payment_method,
    COUNT(*) AS total_orders,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*)
    FROM Orders), 2) AS percentage,
    ROUND(SUM(COALESCE(order_amount,0) - COALESCE(discount,0)), 2) AS total_revenue
FROM Orders
WHERE payment_method IS NOT NULL
GROUP BY payment_method
ORDER BY total_orders DESC;

-- 2. Discount Impact on Revenue

SELECT
    CASE 
        WHEN discount = 0 THEN 'No Discount'
        WHEN discount > 0 AND discount <= 50 THEN 'Low (1-50)'
        WHEN discount > 50 AND discount <= 150 THEN 'Medium (51-150)'
        ELSE 'High (>150)'
    END AS discount_range,
    COUNT(*) AS total_orders,
    ROUND(SUM(order_amount), 2) AS gross_revenue,
    ROUND(SUM(discount), 2) AS total_discount,
    ROUND(SUM(order_amount - discount), 2) AS net_revenue,
    ROUND(AVG(order_amount - discount), 2) AS avg_order_value,
    ROUND(SUM(discount) * 100.0 / SUM(order_amount), 2) AS discount_percentage
FROM Orders
GROUP BY discount_range
ORDER BY discount_range;

-- PHASE 6 — ADVANCED SQL

-- 1.Monthly Revenue Using CTE

WITH
    monthly_revenue
    AS
    (
        SELECT
            YEAR(o.order_date) AS year,
            MONTH(o.order_date) AS month,
            DATE_FORMAT(o.order_date, '%Y-%m-01') AS month_date,
            SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) AS net_revenue,
            COUNT(*) AS total_orders,
            COUNT(DISTINCT o.customer_id) AS unique_customers
        FROM Orders o
        GROUP BY YEAR(o.order_date), MONTH(o.order_date), DATE_FORMAT(o.order_date, '%Y-%m-01')
    )
SELECT month_date,
    year,
    month,
    net_revenue,
    total_orders,
    unique_customers,
    ROUND(net_revenue / total_orders, 2) AS avg_order_value,
    LAG(net_revenue) OVER (ORDER BY month_date) AS prev_month_revenue,
    ROUND((net_revenue - LAG(net_revenue) OVER (ORDER BY month_date)) * 100.0 / LAG(net_revenue) OVER (ORDER BY month_date), 2) AS mom_growth_percentage
FROM monthly_revenue
ORDER BY month_date DESC;


-- 2.Rank Restaurants by Revenue (Window Function)

WITH
    restaurant_revenue
    AS
    (
        SELECT r.restaurant_id,
            r.restaurant_name,
            r.city,
            r.rating,
            SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) AS revenue,
            COUNT(*) AS total_orders
        FROM Orders o
            JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
        GROUP BY r.restaurant_id, r.restaurant_name, r.city, r.rating
    )
SELECT restaurant_id,
    restaurant_name,
    city,
    rating,
    revenue,
    total_orders,
    RANK() OVER (ORDER BY revenue DESC) AS revenue_rank,
    ROUND(revenue * 100.0 / SUM(revenue) OVER (), 2) AS revenue_percentage,
    ROUND(revenue - AVG(revenue) OVER (), 2) AS revenue_vs_avg
FROM restaurant_revenue
ORDER BY revenue DESC;

-- 3.Above Average Revenue Restaurants (Subquery)

SELECT r.restaurant_id,
    r.restaurant_name,
    r.city,
    r.rating,
    SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) AS revenue,
    COUNT(*) AS total_orders
FROM Orders o
    JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city, r.rating
HAVING SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) > 
       (SELECT AVG(total_revenue)
FROM (SELECT SUM(COALESCE(order_amount,0) - COALESCE(discount,0)) AS total_revenue
    FROM Orders
    GROUP BY restaurant_id) AS avg_calc)
ORDER BY revenue DESC;

-- PHASE 7 — DATABASE OBJECTS

-- 1. Create Revenue View

CREATE VIEW vw_restaurant_revenue
AS
    SELECT r.restaurant_id,
        r.restaurant_name,
        r.city,
        r.cuisine,
        r.rating,
        SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) AS total_revenue,
        COUNT(*) AS total_orders,
        ROUND(AVG(o.order_amount - COALESCE(o.discount,0)), 2) AS avg_order_value,
        COUNT(DISTINCT o.customer_id) AS unique_customers
    FROM Orders o
        JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
    GROUP BY r.restaurant_id, r.restaurant_name, r.city, r.cuisine, r.rating;

-- Query the view

SELECT *
FROM vw_restaurant_revenue
ORDER BY total_revenue DESC;
-- 2.Stored Procedure: Get Top N Restaurant
-- 2. Stored Procedure: Get Top N Restaurants by Revenue


-- 2. Stored Procedure: Get Top N Restaurants by Revenue

CREATE PROCEDURE sp_get_top_restaurants(IN top_n INT)
BEGIN
    SELECT r.restaurant_id,
        r.restaurant_name,
        r.city,
        r.cuisine,
        r.rating,
        SUM(COALESCE(o.order_amount,0) - COALESCE(o.discount,0)) AS total_revenue,
        COUNT(*) AS total_orders,
        COUNT(DISTINCT o.customer_id) AS unique_customers,
        ROUND(AVG(o.order_amount - COALESCE(o.discount,0)), 2) AS avg_order_value
    FROM Orders o
        JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
    GROUP BY r.restaurant_id, r.restaurant_name, r.city, r.cuisine, r.rating
    ORDER BY total_revenue DESC
    LIMIT top_n;
END;

-- Call the procedure

CALL
    sp_get_top_restaurants
    (10);

-- PHASE 8-- Performance Optimization

-- Index on order_date (for monthly reports)

CREATE INDEX idx_order_date ON Orders(order_date);
-- Index on customer_name (for joins)
CREATE INDEX idx_customer_name ON Customers(name);
-- Index on restaurant_name
CREATE INDEX idx_restaurant_name ON Restaurants(restaurant_name);

-- PHASE 9 —Automation Logic
-- TRIGGER 1 — Prevent Negative Discount`dd
-- PHASE 9 — Automation Logic
-- TRIGGER 1 — Prevent Negative Discount
CREATE TRIGGER trg_prevent_negative_discount
BEFORE
INSERT ON
Orders
FOR
EACH
ROW
BEGIN
    IF NEW.discount < 0 THEN
        SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT
    = 'Error: Discount cannot be negative';
END
IF;
    
    IF NEW.discount > NEW.order_amount THEN
        SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT
= 'Error: Discount cannot exceed order amount';
END
IF;
END;

-- TRIGGER 2 — Prevent Negative Order Amount
CREATE TRIGGER trg_prevent_negative_order_amount
BEFORE
INSERT ON
Orders
FOR
EACH
ROW
BEGIN
    IF NEW.order_amount <= 0 THEN
        SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT
    = 'Error: Order amount must be greater than 0';
END
IF;
END;

-- TRIGGER 3 — Update Order Timestamp on Modification

CREATE TRIGGER trg_update_order_timestamp
BEFORE
UPDATE ON Orders
FOR EACH ROW
BEGIN
    SET NEW
    .order_date = NOW
    ();
END;

-- TRIGGER 2 — Delivery Delay Warning

CREATE TRIGGER trg_delivery_delay_warning
BEFORE UPDATE ON Orders
FOR EACH ROW
BEGIN
    DECLARE delay_minutes INT;
    
    IF NEW.delivery_time IS NOT NULL AND OLD.delivery_time IS NULL THEN
        SET delay_minutes = NEW.delivery_time;
        
        IF delay_minutes > 60 THEN
            INSERT INTO delivery_alerts (order_id, alert_type, alert_message, created_at)
            VALUES (NEW.order_id, 'DELAY_WARNING', 
                    CONCAT('Order ', NEW.order_id, ' delayed by ', delay_minutes, ' minutes'),
                    NOW());
        END IF;
    END IF;
END;

-- Create delivery_alerts table to store warnings

CREATE TABLE IF NOT EXISTS delivery_alerts (
    alert_id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    alert_type VARCHAR(50),
    alert_message VARCHAR(255),
    created_at DATETIME,
    FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);
